<?php

declare(strict_types=1);

namespace SignerPHP\Infrastructure\Native\Service;

use SignerPHP\Application\DTO\ProtectionOptionsDto;
use SignerPHP\Domain\Exception\ProtectionProcessException;
use SignerPHP\Infrastructure\Native\Contract\CommandExecutorInterface;
use SignerPHP\Infrastructure\Native\Contract\PdfProtectionApplierInterface;

final class QpdfPdfProtectionApplier implements PdfProtectionApplierInterface
{
    public function __construct(private readonly CommandExecutorInterface $commandExecutor = new ShellCommandExecutor) {}

    public function apply(string $pdfContent, ProtectionOptionsDto $options): string
    {
        $tmpDir = sys_get_temp_dir();
        $inputFile = $this->createTempFile($tmpDir, 'pdf-protect-in');
        $outputFile = $this->createTempFile($tmpDir, 'pdf-protect-out');

        file_put_contents($inputFile, $pdfContent);

        try {
            $command = $this->buildQpdfCommand($inputFile, $outputFile, $options);
            $this->commandExecutor->run($command, 'Could not apply PDF protection using qpdf.');

            $protectedContent = file_get_contents($outputFile);
            if ($protectedContent === false || $protectedContent === '') {
                throw new ProtectionProcessException('Could not read protected readonly PDF content generated by qpdf.');
            }

            return $protectedContent;
        } finally {
            @unlink($inputFile);
            @unlink($outputFile);
        }
    }

    private function createTempFile(string $tmpDir, string $prefix): string
    {
        $path = tempnam($tmpDir, $prefix);
        if ($path === false) {
            throw new ProtectionProcessException('Could not create temporary files for PDF protection.');
        }

        return $path;
    }

    private function buildQpdfCommand(string $inputFile, string $outputFile, ProtectionOptionsDto $options): string
    {
        $ownerPassword = $options->ownerPassword ?? bin2hex(random_bytes(16));
        $permissions = $this->buildPermissionOptions($options);

        return sprintf(
            'qpdf --encrypt %s %s %d %s -- %s %s',
            escapeshellarg($options->userPassword),
            escapeshellarg($ownerPassword),
            $options->keyLengthBits,
            implode(' ', $permissions),
            escapeshellarg($inputFile),
            escapeshellarg($outputFile),
        );
    }

    /**
     * @return array<int, string>
     */
    private function buildPermissionOptions(ProtectionOptionsDto $options): array
    {
        $permissionOptions = [
            '--print='.($options->allowPrint ? 'full' : 'none'),
            '--extract='.($options->allowCopy ? 'y' : 'n'),
            '--accessibility=y',
        ];

        if ($options->allowModify) {
            $permissionOptions[] = '--modify=all';
            $permissionOptions[] = '--annotate=y';
            $permissionOptions[] = '--form=y';
            $permissionOptions[] = '--assemble=y';
            $permissionOptions[] = '--modify-other=y';
        } else {
            $permissionOptions[] = '--modify=none';
            $permissionOptions[] = '--annotate=n';
            $permissionOptions[] = '--form=n';
            $permissionOptions[] = '--assemble=n';
            $permissionOptions[] = '--modify-other=n';
        }

        if (! $options->encryptMetadata) {
            $permissionOptions[] = '--cleartext-metadata';
        }

        if ($options->keyLengthBits === 128) {
            $permissionOptions[] = '--use-aes=y';
        }

        return $permissionOptions;
    }
}
